---
- name: Uninstalling Apache MSI
  hosts: all
  vars: 
    apache_path: "C:\ansible_examples\httpd-2.2.25-win32-x86-no_ssl.msi"
  tasks:
    - name: Uninstall Apache MSI
      win_package:
        path: {{ apache_path }}
        state: absent